version: '3.8'
services:
    database-service:
        image: python:3.12.12-slim
        restart: always 
        volumes: 
            - ./database/code:/code
            - ./database/requirements.txt:/requirements.txt
            - ./database/run.sh:/run.sh
        command: sh run.sh
    postgres:
        image: postgres 
        restart: always
        shm_size: 128mb 
        secrets:
            - postgres_password
        volumes:
            - pgdata:/var/lib/postgresql
        env_file:
            - postgress.env
        environment:
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always 
        secrets:
            - pgpass
        volumes:
            - ./pgadmin/servers.json:/pgadmin4/servers.json:ro
            - pgadmindata:/var/lib/pgadmin
        env_file:
            - pgadmin.env
        ports:
            - 8080:80

volumes:
    pgdata:
    pgadmindata:

secrets:
    postgres_password:
        file: ./secrets/postgres_password.txt
    pgpass:
        file: ./secrets/pgpass

