version: '3.8'
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  database-viewer:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 8080

    