version: '3.8'

services:
  api-service:
    container_name: api_service
    build:
      context: api/
    ports: 
      - "8000:8000"
    env_file:
      - api/api.env
    restart: on-failure
    volumes: 
      - ./api/code:/code
    command: ["fastapi", "run", "main.py", "--port", "8000"]

  postgres:
    container_name: postgres
    image: postgres:17.1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data