version: '3.8'

services:
  api-service:
    container_name: api_service
    build:
      context: api/
    ports: 
      - "8000:8000"
    env_file:
      - api/api.env
    restart: on-failure
    volumes: 
      - ./api/code:/code
    command: ["fastapi", "run", "main.py", "--port", "8000"]

