version: '3.8'
services:
    database-service:
        image: python:3.12.12-slim
        restart: always 
        volumes: 
            - ./database/code:/code
            - ./database/requirements.txt:/requirements.txt
            - ./database/run.sh:/run.sh
        command: sh run.sh
    postgres:
        image: postgres 
        restart: always
        shm_size: 128mb 
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: temp
            POSTGRES_PASSWORD: temp 
        ports:
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4:latest
        restart: always 
        environment:
            PGADMIN_DEFAULT_EMAIL: 'temp@temp.com'
            PGADMIN_DEFAULT_PASSWORD: temp
        ports:
            - 8080:80

volumes:
    pgdata:
