version: '3.8'

services:
  api-service:
    container_name: api_service
    build:
      context: api/
    ports: 
      - "8000:8000"
    env_file:
      - api/api.env
    restart: on-failure
    volumes: 
      - ./api/code:/code
    command: ["fastapi", "run", "main.py", "--port", "8000"]

  database-service:
    container_name: database_service
    build:
      context: database_service/
    env_file:
      - database_service/database.env
    restart: on-failure
    volumes: 
      - ./database_service/code:/code
    command: bash run.sh

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /home/im-ud/Documents/Projects/Volumes/postgres_data_budget_beacon:/var/lib/postgresql/data
    env_file: 
      - database_service/database.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always 
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8888:80
    depends_on:
      - postgres
