"""create spaces tables

Revision ID: 4be2166549b3
Revises: b7e6e56e75d2
Create Date: 2026-04-26 02:09:45.275726

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4be2166549b3"
down_revision: Union[str, Sequence[str], None] = "b7e6e56e75d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spaces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("type IN ('personal','shared')", name="ck_spaces_type"),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spaces_created_by_user_id"),
        "spaces",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_spaces_id"), "spaces", ["id"], unique=False)
    op.create_index(op.f("ix_spaces_name"), "spaces", ["name"], unique=False)
    op.create_table(
        "space_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("space_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner','editor','viewer')", name="ck_space_members_role"
        ),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["spaces.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "space_id", "user_id", name="uq_space_members_space_id_user_id"
        ),
    )
    op.create_index(op.f("ix_space_members_id"), "space_members", ["id"], unique=False)
    op.create_index(
        op.f("ix_space_members_space_id"), "space_members", ["space_id"], unique=False
    )
    op.create_index(
        op.f("ix_space_members_user_id"), "space_members", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_space_members_user_id"), table_name="space_members")
    op.drop_index(op.f("ix_space_members_space_id"), table_name="space_members")
    op.drop_index(op.f("ix_space_members_id"), table_name="space_members")
    op.drop_table("space_members")
    op.drop_index(op.f("ix_spaces_name"), table_name="spaces")
    op.drop_index(op.f("ix_spaces_id"), table_name="spaces")
    op.drop_index(op.f("ix_spaces_created_by_user_id"), table_name="spaces")
    op.drop_table("spaces")
    # ### end Alembic commands ###
