FROM python:3.12-slim-bookworm

WORKDIR /fastapi 

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY ./api/requirements.api.txt .

RUN pip install --no-cache-dir -r requirements.api.txt

COPY ./api .
COPY ./config/settings.py .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]